
stages:
  - release_customize_sdk

.release_sdk_template: &release_sdk_template
  variables:
    PACK_NAME: "release_sdk_template"
  stage: release_customize_sdk	
  tags:
    - windows_tc32_test
  script:
    - sdk_release_customize.sh ./release_sdk_config
  artifacts:
    name: "$PACK_NAME"
    paths:
    - chip/
    - common/
    - demo/
    - doc/
    - project/
    - README.md
  when: manual


    
release_sdk_S1:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b85m_driver_sdk_B80_S1"

release_sdk_S2:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b85m_driver_sdk_B80_S2"

release_sdk_S3:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b85m_driver_sdk_B80_S3"

release_sdk_otp_S0:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b85m_driver_sdk_B80_S0_OTP_NO_RET_NO_EXT32K"

release_sdk_otp_S1:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b85m_driver_sdk_B80_S1_OTP_NO_RET_NO_EXT32K"

release_sdk_otp_S2:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b85m_driver_sdk_B80_S2_OTP_NO_RET_NO_EXT32K"

release_sdk_otp_S3:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b85m_driver_sdk_B80_S3_OTP_NO_RET_NO_EXT32K"
